# Generated by Django 2.0 on 2022-01-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_merge_20220105_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='puntuacion15',
            field=models.BooleanField(default=False, help_text='Check the box to create a question of Very Bad/Very Good', verbose_name='Answers Very Bad/Very Good'),
        ),
    ]
