# Generated by Django 2.0 on 2022-01-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_question_puntuacion15'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='YNNS_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='binary_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='puntuacion15',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('NO', 'Create your questions below'), ('BI', 'Binary Question'), ('YN', 'Yes/No Question'), ('BG', 'Very Bad/ Very Good Question')], default='NO', max_length=2),
        ),
    ]
