# Generated by Django 2.0 on 2022-01-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_auto_20220108_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='seat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='voting_type',
            field=models.SmallIntegerField(choices=[(1, 'Dhont'), (2, 'Paridad'), (3, 'Borda')], default=1),
        ),
    ]
