# Generated by Django 2.0 on 2022-01-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_auto_20220108_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='seat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
