# Generated by Django 2.0 on 2022-01-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_auto_20220108_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voting_type',
            field=models.SmallIntegerField(choices=[(0, 'Default'), (1, 'Dhont'), (2, 'Paridad'), (3, 'Borda')], default=1),
        ),
    ]
