# Generated by Django 2.0 on 2022-01-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_auto_20220109_1453'),
        ('voting', '0016_auto_20220108_1217'),
    ]

    operations = [
    ]
